# https://longhorn.io/docs/1.6.2/deploy/install/install-with-helm/

# Run on all Node
- name: Longhorn - OS Prerequisites
  ansible.builtin.include_tasks:
    file: 'longhorn-os.yml'
    apply:
      tags:
        - longhorn-os
        - os

# Run once (first server)
- name: Longhorn - Install
  when: 'ans_e_longhorn_version is defined and ans_e_longhorn_version != ""'
  run_once: true
  ansible.builtin.include_tasks:
    file: 'longhorn-install.yml'
    apply:
      tags: longhorn-install

# Run once (Conf)
- name: Longhorn - Ingress Conf
  when: 'ans_e_longhorn_version is defined and ans_e_longhorn_version != ""'
  run_once: true
  ansible.builtin.include_tasks:
    file: 'longhorn-conf-ingress.yml'
    apply:
      tags: longhorn-conf

# Run once (Conf)
- name: Longhorn - Backup Conf Conf
  when: 'ans_e_recurring_job_cron is defined and ans_e_recurring_job_cron != ""'
  run_once: true
  ansible.builtin.include_tasks:
    file: 'longhorn-conf-backup.yml'
    apply:
      tags: longhorn-conf