---
- hosts: hosts
  become: true
  vars:
    ansible_user: root # first run if the admin user was not yet created, second run the ssh_user_name
    # ansible_user: {{ ssh_user_name }} # second run
  roles:
    - role: os
      vars:
        ssh_user_name: beau # the admin user
        ssh_user_key: ssh-rsa AAAAxxxx # the public key (private key should be in the agent)
        os_packages:
          - jq
          - wget
          - lsof # lsof (open file)
          - zip
          - unzip
          - sshpass
          - nmap # Added nmap to tbe able to scan the open port at the command line
          - sysstat # (for process monitoring and stat, pidstat)
          - bzip2 # to unzip bz2)
          - telnet
          - sudo
          - whois
          - netcat-openbsd
          - bind9-utils # dig
