#!/usr/bin/env bash

set -TCEeuo pipefail

SCRIPT_DIR=$(dirname "$(realpath "$0")")

pushd "$SCRIPT_DIR/../extensions"

molecule --ans-x-without-pass reset && molecule --ans-x-without-pass converge

popd