- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Assert group existence
      ansible.builtin.assert:
        that: "'molecule' in groups"
        fail_msg: |
          molecule group was not found inside inventory groups: {{ groups }}

- name: Converge
  hosts: molecule
  gather_facts: true
  vars:
    ans_x_hostname: sub.example.com
    ans_x_admin_username: admin
    ans_x_admin_public_key: ssh-rsa AAAAB3NzaC1yxxxx
  tasks:
    - name: Check uname
      ansible.builtin.raw: uname -a
      register: result
      changed_when: false

    - name: Print some info
      ansible.builtin.assert:
        that: result.stdout | regex_search("^Linux")

    - name: Testing Ans-x-os
      ansible.builtin.include_role:
        name: gerardnico.ansible_x_collection.ans_x_os
        #tasks_from: main.yml
