---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Replace this task with one that validates your content
      ansible.builtin.debug:
        msg: "This is the effective test"
#    - name: Include a playbook from a collection
#      ansible.builtin.import_playbook: gerardnico.ansible_x_collection.playbook-os-example
    - name: Testing role
      ansible.builtin.include_role:
        name: gerardnico.ansible_x_collection.ans_x_os
        #tasks_from: main.yml
