# https://ansible.readthedocs.io/projects/molecule/getting-started/#inspecting-the-moleculeyml
---
# Driver provider
# https://ansible.readthedocs.io/projects/molecule/configuration/#driver
#
driver:
  name: docker
# Platforms define the instances to be tested, and the groups to which the instances belong.
# Instance to create (manage the type of distribution CentOS, Fedora, Debian)
# https://ansible.readthedocs.io/projects/molecule/configuration/#platforms
platforms:
  # These properties are literally read by tasks in `create.yml`
  # It's a property of community docker
  # * name is the name of the container
  # * image ...
  # You could have more than one image started
  # The command is hard written as `sleep 1d`
  #
  # There is also a docker driver which is completely other thing
  # https://github.com/ansible-community/molecule-plugins/tree/main/src/molecule_plugins/docker
  #

  - name: molecule-debian
    image: ghcr.io/gerardnico/molecule-debian:12.8
    hostname: kube.example.com
    pre_build_image: true
    override_command: false
    privileged: true
    published_ports:
      - "6443:6443"
      - "80:80"
      - "443:443"
    # Why run and tmp as tmpfs ???
    tmpfs:
      - /run
      - /tmp
    # Inventory group
    groups:
      - server
    volumes:
      - /sys/fs/cgroup/warewulf.scope:/sys/fs/cgroup:rw

dependency:
  name: galaxy
  options:
    # Path relative to where you start molecule
    # ie from extensions
    requirements-file: molecule/default/requirements.yml
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: root
        ans_x_os_packages:
          - curl # needed to download k3s
    host_vars:
      # setting for the docker/platform instance named 'molecule-debian'
      molecule-debian:
        ans_x_hostname: kube.example.com
