


- name: 'Modify hostname'
  when: 'ansible_virtualization_type != "docker"'
  hostname:
    name: '{{ ans_x_os_hostname }}'

# On docker, the /etc/file is locked
# In test with molecule, we may use `molecule_driver_name == 'docker`
# https://ansible.readthedocs.io/projects/molecule/configuration/#molecule.interpolation.Interpolator.interpolate
#- name: 'Check Hostname'
#  when: 'ansible_virtualization_type == "docker" and ansible_fqdn != ans_x_os_hostname'
#  fail:
#    msg: "On a docker container, the hostname is ({{ ansible_fqdn }}). It should be set to ({{ ans_x_os_hostname }}) via the `hostname` flag"

- name: Configure the IP Name
  # On docker when we test with Molecule,
  # the /etc/hosts file is blocked. We get this error, and we can;t modify it
  # The error was: OSError: [Errno 16] Device or resource busy: b'/etc/.ansible_tmpw88krd6thosts' -> b'/etc/hosts'
  #
  # They mount it, we could check that ??
  # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-etc_hosts
  when: 'ansible_virtualization_type != "docker"'
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK Hostname"
  with_items:
    - { name: "{{ ans_x_os_hostname }}  {{ ans_x_os_hostname.split('.', 1)[0] }}", ip: '{{ ansible_default_ipv4.address }}' }


