
- name: 'Modify hostname'
  hostname:
    name: '{{ hostname }}'

- name: Configure the IP Name
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK Hostname"
  with_items:
    - { name: "{{ hostname }}  {{ hostname.split('.', 1)[0] }}", ip: '{{ ansible_default_ipv4.address }}' }


