# https://prometheus.io/docs/introduction/first_steps/

- name: Check if Prometheus is already installed.
  stat:
    path: "{{ ans_e_prometheus_home }}/prometheus"
  register: prometheus
- name: Download
  when: not prometheus.stat.exists
  block:

    - name: Download Prometheus
      get_url:
        url: "{{ ans_e_prometheus_binary_url }}"
        dest: "{{ ans_e_prometheus_install_dir }}/prometheus.tar.gz"
        owner: "{{ ans_e_prometheus_user_name }}"
        group: "{{ ans_e_prometheus_user_group }}"
        checksum: "{{ ans_e_prometheus_checksum }}"

    - name: Unzip Prometheus Binary
      unarchive:
        src: "{{ ans_e_prometheus_install_dir }}/prometheus.tar.gz"
        dest: "{{ ans_e_prometheus_install_dir }}"
        owner: "{{ ans_e_prometheus_user_name }}"
        group: "{{ ans_e_prometheus_user_group }}"
        copy: false
    - name: Move files
      become: yes
      become_user: "{{ ans_e_prometheus_user_name }}"
      shell:
        cmd: "/bin/cp -rf {{ ans_e_prometheus_install_dir }}/{{ ans_e_prometheus_binary_name }}/* {{ ans_e_prometheus_home }}"

- name: Copy the configuration prometheus.yml
  notify: 'restart prom'
  template:
    src: prometheus.yml
    dest: "{{ ans_e_prometheus_home }}/prometheus.yml"
    owner: "{{ ans_e_prometheus_user_name }}"
    group: "{{ ans_e_prometheus_user_group }}"

- name: Copy the systemd prometheus.service file
  notify: 'restart prom'
  template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
    mode: 0644
