- name: Install Git (required for plugin installation)
  ansible.builtin.package:
    name: git
    state: present

- name: Get helm installed version
  ansible.builtin.shell: helm version | grep -oP 'Version:"v\K[0-9.]+'
  register: ans_e_helm_version_output
  changed_when: false
  ignore_errors: yes


- name: Set helm installed version
  when: ans_e_helm_version_output.rc == 0
  set_fact:
    installed_ans_e_helm_version: '{{ ans_e_helm_version_output.stdout }}'

- name: Set helm installed version
  when: ans_e_helm_version_output.rc != 0
  set_fact:
    installed_ans_e_helm_version: '0'

- name: helm version {{ installed_ans_e_helm_version }}
  debug:
    var: installed_ans_e_helm_version

- name: Update node only if needed
  # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/version_test.html
  when: "installed_ans_e_helm_version is version(ans_e_helm_version, '<')"
  block:
    # Ref: https://askubuntu.com/questions/1432705/permission-denied-when-executing-exec-on-tmp-ubuntu-22-04
    - name: Creates tmp directory to avoid sticky problem
      ansible.builtin.file:
        path: /tmp/helm
        state: directory
    # as explained here https://helm.sh/docs/intro/install/#from-script
    - name: Download Helm installation script
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/helm/get_helm.sh
        mode: '0700'

    - name: Run Helm installation script
      # Full command to avoid, no permissions
      ansible.builtin.command: /usr/bin/env bash /tmp/helm/get_helm.sh
      args:
        chdir: /tmp/helm


- name: Install Helm Plugins
  kubernetes.core.helm_plugin:
    plugin_path: '{{ item.plugin_path }}'
    plugin_version: "{{ item.plugin_version | default() }}"
    state: "{{ item.state | default('present') }}"
  with_items: '{{ ans_e_helm_plugins | default([]) }}'
