# Check an allowed user

- name: Parse user
  ansible.builtin.set_fact:
    ans_e_sshd_user: "{{ ans_e_sshd_allowed_user.split('@')[0] }}"

# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/getent_module.html
- name: Check if user exists and can login
  ansible.builtin.getent:
    database: passwd
    key: "{{ item.ansible_facts.ans_e_sshd_user }}"
  register: user_exists
  failed_when: >
    user_exists.failed or
    (ansible_facts['getent_passwd'][item.ansible_facts.ans_e_sshd_user][4] in ['/bin/false', '/usr/sbin/nologin'])