# https://ansible.readthedocs.io/projects/molecule/getting-started/#inspecting-the-moleculeyml
---
# Driver provider
# https://ansible.readthedocs.io/projects/molecule/configuration/#driver
# Delegated driver by default (https://ansible.readthedocs.io/projects/molecule/configuration/#delegated)
driver:
  # v6 made the "delegated" one the default
  # https://ansible.readthedocs.io/projects/molecule/configuration/#delegated
  # Under this driver, it is the developers responsibility to implement the create and destroy playbooks
  name: default
# Platforms define the instances to be tested, and the groups to which the instances belong.
# Instance to create (manage the type of distribution CentOS, Fedora, Debian)
# https://ansible.readthedocs.io/projects/molecule/configuration/#platforms
platforms:
  # These properties are literally read by tasks in `create.yml`
  # It's a property of community docker
  # * name is the name of the container
  # * image ...
  # You could have more than one image started
  # The command is hard written as `sleep 1d`
  #
  # There is also a docker driver which is completely other thing
  # https://github.com/ansible-community/molecule-plugins/tree/main/src/molecule_plugins/docker
  #
  # https://ansible.readthedocs.io/projects/molecule/guides/custom-image/
  # https://ansible.readthedocs.io/projects/molecule/guides/systemd-container/#systemd-container
  - name: molecule-debian
    image: ghcr.io/gerardnico/molecule-debian:12.8
    hostname: kube.example.com

dependency:
  name: galaxy
  options:
    # Path relative to where you start molecule
    # ie from extensions
    requirements-file: molecule/default/requirements.yml
#provisioner:
#  name: ansible
#  config_options:
    # defaults:
      # https://ansible.readthedocs.io/projects/dev-tools/user-guide/testing/#molecule
      # collections_path: ${ANSIBLE_COLLECTIONS_PATH}
      # In bash: export ANSIBLE_COLLECTIONS_PATH=/home/user/working/collections
