# Rotate k3s cert
#
# As stated in the doc: https://docs.k3s.io/cli/certificate#rotating-client-and-server-certificates
#
# Why: k3s introduced a change that needs hard cert rotation
# The discussion https://github.com/k3s-io/k3s/discussions/10024#discussioncomment-12073740
# The changes https://github.com/k3s-io/k3s/commit/caeebc52b772cb76c6113ff0804e9fea12674354


- name: Rotate K3s Servers certificates
  hosts: server
  become: true
  # Servers should be restarted sequentially to avoid etcd learner issues
  # Agents have no such limitation
  serial: 1
  tasks:
    - name: Stop K3s service [server]
      ansible.builtin.systemd:
        state: stopped
        name: k3s
    - name: Rotate Certificates [server]
      shell: |
        k3s certificate rotate
    - name: Start K3s service [server]
      ansible.builtin.systemd:
        state: started
        name: k3s


- name: Restart K3s Agents
  hosts: agent
  become: true
  tasks:
    - name: Stop K3s service [agents]
      ansible.builtin.systemd:
        state: stopped
        name: k3s
    - name: Rotate Certificates [agents]
      shell: |
        k3s certificate rotate
    - name: Start K3s service [agents]
      ansible.builtin.systemd:
        state: started
        name: k3s