# k3s-ansible does not have any restart

- name: Restart K3s Servers
  hosts: server
  become: true
  # Servers should be restarted sequentially to avoid etcd learner issues
  # Agents have no such limitation
  serial: 1
  tasks:
    - name: Restart K3s service [server]
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: k3s


- name: Restart K3s Agents
  hosts: agent
  become: true
  tasks:
    - name: Restart K3s service [agent]
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        name: k3s-agent