# https://ansible.readthedocs.io/projects/molecule/getting-started/
# Testing a role doc: https://ansible.readthedocs.io/projects/dev-tools/user-guide/testing/
---
# if the playbook does not explicitly include_role the role,
# the library and module_utils provided by the role are not available in the playbook by default.
# Ref: the Note of the scenario layout section: https://ansible.readthedocs.io/projects/molecule/getting-started/#the-scenario-layout
- name: Verify
  hosts: all
  become: true
  tasks:
    - name: Initialize role without actually running it
      ansible.builtin.include_role:
        name: gerardnico.ans_x_os
        tasks_from: main.yml
---
- name: Test new role from within this playbook
  hosts: localhost
  gather_facts: false
  vars:
    ansible_user: root # first run if the admin user was not yet created, second run the ssh_user_name
    # ansible_user: {{ ssh_user_name }} # second run
  roles:
    - role: os
      vars:
        ssh_user_name: beau # the admin user
        ssh_user_key: ssh-rsa AAAAxxxx # the public key (private key should be in the agent)
        os_packages:
          - jq
          - wget
          - lsof # lsof (open file)
          - zip
          - unzip
          - sshpass
          - nmap # Added nmap to tbe able to scan the open port at the command line
          - sysstat # (for process monitoring and stat, pidstat)
          - bzip2 # to unzip bz2)
          - telnet
          - sudo
          - whois
          - netcat-openbsd
          - bind9-utils # dig
