# https://longhorn.io/docs/1.6.2/advanced-resources/system-backup-restore/backup-longhorn-system/#using-kubectl-command
apiVersion: longhorn.io/v1beta2
kind: SystemBackup
metadata:
  name: longhorn-system-backup-2
  namespace: '{{ ans_e_longhorn_namespace }}'
spec:
  volumeBackupPolicy: if-not-present